login: &login
  access_key_id: 
  secret_access_key: 

development:
  bucket_name: proactive_technologies_development
  <<: *login
  distribution_domain: 

test:
  bucket_name: proactive_technologies_test
  <<: *login
  distribution_domain: 

production:
  bucket_name: proactive_technologies_production
  <<: *login
  distribution_domain: 
