login: &login
  adapter: mysql2
  host: localhost
  username: root
  password: mpwacc3ss

development:
  database: proactive_technologies_development
  <<: *login

test:
  database: proactive_technologies_test
  <<: *login

production:
  database: proactive_technologies_production
  adapter: mysql2
  host: localhost
  username: root
  password: mpwacc3ss
