login: &login
  adapter: mysql2
  host: localhost
  username: 
  password: 

development:
  database: proactive_technologies_development
  <<: *login

test:
  database: proactive_technologies_test
  <<: *login

production:
  database: proactive_technologies_production
  adapter: mysql2
  host: localhost
  username: 
  password: 
