login: &login
  adapter: mysql
  host: localhost
  username: root
  password: 

development:
  database: proactive_technologies_development
  <<: *login

test:
  database: proactive_technologies_test
  <<: *login

production:
  database: proactive_technologies_production
  adapter: mysql
  host: mysql.mpwstaging.com
  username: proactivedb
  password: pr0activedb1
